### PR TITLE
Install headers, cmake file

### PR DESCRIPTION
**Pull request by yurivict**
Upstreaming changes from the FreeBSD port.

### CODE REVIEW

**Comment by yurivict** [comment]
Ping project owners.

**Comment by COM8** [comment]
Ping @kingkili.

**Comment by KingKili** [comment]
Hmm, the part about the config is valid and should probably be added, but the rest is already logic in master.

**Comment by COM8** [comment]
With #383 I would say all features proposed here have been merged.
I’m closing this.
Feel free to open a new PR if something is missing.

**Pull request closed without merging**
