### PR TITLE
Run compilation and tests with 2 jobs

### PR DESCRIPTION
**Pull request by thedrow**
Travis has ~2 cores and it'd be a shame not to use them.

### CODE REVIEW

**Comment by thedrow** [comment]
Looks like there's a problem with running tests in parallel. Any hints on how to fix this?

**Comment by nabijaczleweli** [comment]
Better option: `-j$(nproc)`

**Comment by thedrow** [comment]
Not on travis. It doesn't report the number of cpus correctly.

**Comment by nabijaczleweli** [comment]
How so?

**Comment by thedrow** [comment]
Because their virtualization technology doesn't override the /proc and /etc/cpuinfo filesystem correctly.

**Comment by whoshuu** [comment]
Hey @thedrow, this looks good. I think running the build in parallel definitely makes sense. Should we just run it with `-j`, where no second argument is specified? `make` will run as many jobs as the system would be able to handle.

As for the tests, it looks like there's no real consistency in which tests are failing, which tells me the issue is in how the test driver (`ctest`) loads and runs the test executables. The embedded mongoose server does use some statics if I recall, so that might be where the issue is? This would require some more investigation.

For now, I think the best thing to do is to remove parallelism for `ctest` and bump it up to the max for `make`. We get definite improvements now and can figure out the other issue later.

What are your thoughts on this?

**Comment by thedrow** [comment]
-j will spawn 32 jobs in Travis as there is no correct CPU information on that environment.
I can remove the parallelism from ctest.

**Comment by whoshuu** [comment]
Looks good, thanks @thedrow for the PR! Merging in now.

**Pull request merged**
