### PR TITLE
Split a request preparation from its execution

### PR DESCRIPTION
**Pull request by jsouquie**
I'm currently prototyping the use of cpr with multiple parallel requests in a single thread, through the curl_multi_socket_action() API.
This means I need to decouple the request execution (curl_easy_perform) from its preparation and completion.
Would you consider upstreaming the included changes that allow this decoupling ?

Notes for further:
* having response_string_ as an attribute of Session should allow a trivial implementation of #530.
* there is currently a lot of similarity between makeRequest() and makeDownloadRequest(). I'm not sure if the few differences are intentional or a result of copy-paste gone wrong. The prepareCommon() method I introduced would be a good way to reduce copy-paste decay if the differences were not intentional.

### CODE REVIEW

**Comment by jsouquie** [comment]
I forgot to comment about how these new API are used. It look something like this:
```
cpr::Url url = cpr::Url{"http://www.httpbin.org/get"};
cpr::Parameters parameters = cpr::Parameters{{"hello", "world"}};
cpr::Session session;
session.SetUrl(url);
session.SetParameters(parameters);

session.PrepareGet();
CURLcode cc = my_curl_multi_engine(session.GetCurlHolder()->handle);
cpr::Response r = session.Complete( cc )

std::cout << r.url << std::endl;
```

**Review by COM8 — CHANGES_REQUESTED** [review]
Thanks for contributing.
I really like your changes here.
Only a few minor things:
* Could you please create a PR against the `gh-pages` branch and add documentation for your feature (chapter [`Session Object`](https://whoshuu.github.io/cpr/advanced-usage.html#session-objects)).
* Add support and documentation for #530.

**Comment by COM8** [comment]
* And add a couple of test cases so we can make sure everything works like expected if somebody uses only the new API.

**Comment by jsouquie** [comment]
I'm thinking about #530: as I said, the implementation is trivial after this PR, but I'm unsure about how to expose this capability.
Adding a `SetResponseCapacity(const ResponseCapacity& capacity)` and a matching `SetOption()` seems a bit off to me. Mainly because all other options are directly related to curl itself, whereas this one is related to cpr only.

**Review by COM8 — APPROVED** [review]
Looks good. Thanks.

**Comment by COM8** [comment]
> 
> 
> I'm thinking about #530: as I said, the implementation is trivial after this PR, but I'm unsure about how to expose this capability.
> Adding a `SetResponseCapacity(const ResponseCapacity& capacity)` and a matching `SetOption()` seems a bit off to me. Mainly because all other options are directly related to curl itself, whereas this one is related to cpr only.

I agree something like `SetResponseCapacity(const ResponseCapacity& capacity)` does not make sense here. I'd say this should be something that can only be set in a `cpr::Session` object directly.
So I suggest we push this back and ignore it in this PR.

**Comment by COM8** [comment]
Great work.

**Pull request merged**
