### PR TITLE
[WIP] Updated curl from 7.56.0 to 7.69.1

### PR DESCRIPTION
**Pull request by COM8**
Updated curl from `7.56.0` to `7.69.1`.

### Related Issues
* #342 
* #387 

### Related PRs
* #343

### Changes
* Updated curl from `7.56.0` to `7.69.1`
* Switched from a self maintained fork of `mongoose` to the official `mongoose` repo
* Switched from a self maintained fork of `googletest` to the official `googletest` repo
* Updated all unit tests to the latest version of the `mongoose` server
* Refactored the `mongoose` http web server

### TODO
- [x] ~~Fix Windows linker errors~~
- [x] ~~Fix MacOS not executing tests~~
- [x] Fix the segfault caused by `ssl-test`

### CODE REVIEW

**Comment by tstack** [comment]
Hmm, what's going on with the appveyor build here?  Why would the mongoose build be affected?

**Comment by COM8** [comment]
I don't know for sure.
But I guess it's caused by compiling under Windows with an rather old compiler (VS 2015).
I'm currently investigating it.

**Comment by COM8** [comment]
Validated everything again with VS2019 and it looks like it's working like it should.
Only one problem: the tests fail, since it somehow does not build `gtest`.
**But** `mongoose` and `cpr` are building just fine.

Perhaps we should switch to an more up to date compiler (for Windows and Linux) and build system (perhaps GitHub actions).

**Comment by COM8** [comment]
@tstack 
Do not include this PR if you want to create a new tag.
I can confirm everything works like it should on older VS compilers but on newer ones other stuff is breaking.
I had to update `googletest` since the [fork](https://github.com/whoshuu/googletest), we are using is so outdated it is not compatible with VS <= 2017 due to deprecated macros.

I also updated `mongoose` to a release **1080** commits more into the future.
**But** this is breaking the test server since `mongoose` changed so much.
In theory it complies, but the tests do not.

I'm updating the server and then we can create a new tag again when this PR is ready to be merged.

Any concerns?

**Comment by tomay3000** [comment]
I am just curious here,
Starting with C++11 std::string::data() is guaranteed to have a null ('\0') terminating character which means it is the same as std::string::c_str().
If this is just for consistency and readability then this should be OK.

**Comment by COM8** [comment]
@tomay3000 do you have any references for this?
Based on the official documentation over at [cppreference.com](https://en.cppreference.com/w/cpp/string/basic_string/data) it is not guaranteed.
Yes, there are implementations of `std::string` that handle it like that, but I can not find any general reference for it.

> The pointer is such that the range [data(); data() + size()) is valid and the values in it correspond to the values stored in the string. 

Source: [cppreference.com](https://en.cppreference.com/w/cpp/string/basic_string/data)

**Comment by tomay3000** [comment]
> @tomay3000 do you have any references for this?

Based on `std::string::data()` official documentation over at [cppreference.com](https://en.cppreference.com/w/cpp/string/basic_string/data):

Description | C++11
-- | --
The returned array **is not required** to be **null-terminated**.If empty() returns true, the pointer is a non-null pointer that should not be dereferenced. | **UNTIL C++11**
The returned array **is null-terminated**, that is, `data()` and `c_str()` perform the same function.If empty() returns true, the pointer points to a single null character. | **SINCE C++11**
---
And on `std::string::c_str()` official documentation over at [cppreference.com](https://en.cppreference.com/w/cpp/string/basic_string/c_str):

Description | C++11
-- | --
`c_str()` and `data()` perform **THE SAME** function. | **SINCE C++11**
---
Most of C++11 code uses both functions only for consistency, though they are the same.

Meaning:
- `std::string::data()` is meant to be used when retrieving data to be used as data (as binary)
- `std::string::c_str()` is meant to be used when retrieving data to be used as C-String.

It is the C++11 stand that messed it up when it was ok prior to C++11.

TIA.

**Comment by COM8** [comment]
You are right.
So, this change was not necessary.
I still think it is clearer to read in my eyes.

**Comment by tomay3000** [comment]
> You are right.
> So, this change was not necessary.
> I still think it is clearer to read in my eyes.

Ok, and BTW **curl v7.71.0**, has been released today.

**Pull request merged**
