### PR TITLE
add bearer token

### PR DESCRIPTION
**Pull request by waltronix**
Hi,

I prepared a pull request concerning #318 
Can you give me some feedback, if testing is ok for it, please.

Regards
Andreas

### CODE REVIEW

**Comment by waltronix** [comment]
I see, I have also to adapt the test server.

**Review by COM8 — APPROVED** [review]

**Comment by COM8** [comment]
Great PR. Thanks!

**Comment by COM8** [comment]
Only one thing. Please create a PR against the [gh-pages](https://github.com/whoshuu/cpr/tree/gh-pages) branche and add documentation for this PR.

**Comment by waltronix** [comment]
Thanks, I'm glad to support a bit.

I added a merge request for the documentation (#469), hope it's ok.

**Pull request merged**
