### PR TITLE
Simple try at conan package file + add install commands for cmake.

### PR DESCRIPTION
**Pull request by deblauwetom**
I saw the other attempt, but I wanted to show that it could be simpler, afaik about conan. So if nothing else, it can be inspirational :)

### CODE REVIEW

**Comment by tastytea** [comment]
Please use [GNUInstallDirs](https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html). It is portable and the variables can be overridden.

**Comment by jgsogo** [comment]
Hi! We are adding `cpr` to  `conan-center-index` here https://github.com/conan-io/conan-center-index/pull/450. As you can see there is a lot of people from the community contributing with new recipes for different libraries and maintaining them. We think that having this kind of central repository is the way to go for _community packages_, it makes it easier to keep recipes up to date.

**Comment by jgsogo** [comment]
It's been merged, now you can install the library using

```
conan install cpr/1.3.0@
```

**Comment by COM8** [comment]
Ping @kingkili.

**Pull request closed without merging**
