### PR TITLE
Escape Parameter key and values

### PR DESCRIPTION
**Pull request by sean-**
Also, when a parameter doesn't include a Value, don't append an =.

### CODE REVIEW

**Comment by joequery** [comment]
I would recommend not changing file structure as part of this PR. A majority of the diff for this PR is related to changing the structure, not the actual param escaping.

**Comment by joequery** [comment]
There also doesn't seem to be a test, so I'd recommend throwing one in as well.

**Comment by whoshuu** [comment]
@joequery, yeah I actually am pulling in each of these commits one by one in the master branch. I've added a test for the functional changes in `Parameters`, and will be evaluating the rest of the changes in a bit.

**Comment by joequery** [comment]
:+1:

**Comment by whoshuu** [comment]
Hey @sean-, I think the last thing I wanna pull out of this is the change from having everything in `include/` and putting it into `include/cpr/` instead. I'll try to get this in some time before the end of the day. I'll let you know when that happens and you can close this pull request.

Don't worry, your contributions will be reflected in the git history even if we don't merge this pull request in proper.

Appreciate all your help!

**Comment by whoshuu** [comment]
I've got your commits merged in:
https://github.com/whoshuu/cpr/commit/e326f081742d00c2649436f9c22f1cc364f6ba71
https://github.com/whoshuu/cpr/commit/afb026bdfe0fb37baa1e3c5e893f0701c2f1ebb7
https://github.com/whoshuu/cpr/commit/305c446e0dba86bd32e184a077e5f0af200ae9ed

The rest I don't plan on changing, so this PR can be closed now.

Thanks for your efforts @sean-!!

**Comment by whoshuu** [comment]
Closing this now. Thanks for your contributions @sean-!

**Pull request closed without merging**
