### PR TITLE
Add support for CURLOPT_PINNEDPUBLICKEY

### LINKED ISSUE #535: Add support for curl pinned public key (ssl pinning)
With the option `CURLOPT_PINNEDPUBLICKEY` set, more information https://curl.se/libcurl/c/CURLOPT_PINNEDPUBLICKEY.html.

### PR DESCRIPTION
**Pull request by alysondeives**
This PR closes #535

### CODE REVIEW

**Review by COM8 — APPROVED** [review]
Great work. Thanks!

**Comment by COM8** [comment]
Could you please create a PR for documentation in the gh-pages branche?
https://whoshuu.github.io/cpr/advanced-usage.html#https-options

**Comment by alysondeives** [comment]
> Could you please create a PR for documentation in the gh-pages branche?
> https://whoshuu.github.io/cpr/advanced-usage.html#https-options

Sure! I will work on it.

**Comment by COM8** [comment]
The CI fails currently because it's missing the `server.pubkey` file.
Did you forget to commit this file?

**Comment by alysondeives** [comment]
> The CI fails currently because it's missing the `server.pubkey` file.
> Did you forget to commit this file?

Sorry, I forgot to add it :facepalm:. 
I updated my commit.

**Pull request merged**
