### PR TITLE
Added iterator interface to Cookies class.

### PR DESCRIPTION
**Pull request by nshcat**
Proposed fix for issue #123 .

### CODE REVIEW

**Comment by whoshuu** [comment]
Hey @nshcat, thanks for the pull request. I've been swamped recently with work stuff, but I've gotten some spare cycles to review pull requests.

One question about what you've added here. I'm not a language expert, not a compilers wizard, so if you could tell me the portability implications of your `auto method_name() -> return_type` syntax, that would really help move things along. Is this a c++14 construction? What compilers currently support this? What's the complexity/cost of degrading this back to an older syntax?

Any help would be appreciated. Thanks once again!

**Comment by nshcat** [comment]
Well, it is a C++14 feature. I didn't realize that when I first wrote this, so my apologies for that.

The syntax is called "trailing return type". One example in my pull request:

**Comment by nshcat** [comment]
I just realized that the "trailing return type" syntax I used is indeed part of C++14. Welp, I guess that happens when one starts C++ with C++14.

That syntax is basically used as syntactic sugar in a few egde cases when using a class-local type alias in a method's implementation, like so:

```c++

**Comment by nshcat** [comment]
I just realized that the "trailing return type" syntax I used is indeed part of C++14. Welp, I guess that happens when one starts C++ with C++14.

That syntax is basically used as syntactic sugar in a few egde cases when using a class-local type alias in a method's implementation, like so:

```c++
// Header
class X
{
      using my_type = int;

      my_type test();
};

// Source file
X::my_type X::test() { /* ... */  };
```

This is the way this would be done in C++11. Note that we need to specify the scope wherein `my_type` resides, because at the point where `X::my_type` is parsed, `X::test` was not yet encountered and thus the compiler does not know yet that we are in fact inside class `X` . (C++ is parsed line by line, from left to right).

Trailing return type can fix this, as we are declaring the return type _after_ mentioning the containg class, thus making the implementation look less cluttered:

But yea, since this is C++14 I am going to replace it with the C++11 implementation.

**Comment by erengy** [comment]
I wonder if it'd be a better idea to ditch the private `map_` at this point and use `class Cookies : public std::map<std::string, std::string>` instead. It'd introduce modifier functions too, which may help with issues such as #102 and #107.

**Comment by whoshuu** [comment]
@erengy, I think you're probably right in this case. I looked over the [RFC for cookies](https://tools.ietf.org/html/rfc6265) and it looks like some cookies are case insensitive. That's unfortunate but the current implementation inside cpr doesn't use the case insensitive map in the first place. There's no added disadvantage to just exposing a map as a public field in the `Cookies` class.

One question I'd like to generate more discussion on is if we should just make `Cookies` a typedef of a `std::map<std::string, std::string>`. That would reduce some complexity at the cost of losing some utility (such as having to make `GetEncoded` a non-member function). What do you all think of that?

**Comment by dima74** [comment]
@whoshuu, I think we should make `Cookies` a typedef of a `std::map<std::string, std::string>`. It would be very elegant.

**Comment by COM8** [comment]
Fixed by #365 .

**Pull request closed without merging**
